
spring:
  profiles:
    active: local
  application:
    name: yu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # 文件上传设置更大的体积
  servlet:
    multipart:
      max-file-size: 10MB

# 通用配置项
server:
  port: 8080
  servlet:
    context-path: /api

# MyBatis-Plus 通用配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j 通用配置
knife4j:
  enable: true
  openapi:
    title: 鱼图后端接口文档
    version: v1.0
    description: 鱼图项目的后端接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller

